import type { Metadata } from 'next';


import { Inter as FontSans } from "next/font/google";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import "@/app/globals.css";
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
			<body className={`${fontSans.variable} min-h-screen bg-background antialiased`}>
				{children}
				<div className='w-32 bg-red-300 h-32'>
					hello root layout
				</div>
			</body>
    </html>
  )
}
